=== netarchivesuite/netarchivesuite/harvester/harvester/src/test/resources/dk/netarkivet/harvester/harvesting/data/launcher/originals/heritrix_settings.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
        
    <xs:annotation>
        <xs:documentation xml:lang="en"> Schema for heritrix settings.
        Crawl job order files are instances of this schema.

        $Id$ 
        </xs:documentation>
    </xs:annotation>


    <xs:element name="crawl-order">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="meta"/>
                <xs:element name="controller" type="basicTypes"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="id">
            <xs:selector xpath=".//newObject"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="crawl-settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="meta"/>
                <xs:element ref="object" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="meta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="operator" type="xs:string"/>
                <xs:element name="organization" type="xs:string"/>
                <xs:element name="audience" type="xs:string"/>
                <xs:element name="date" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="boolean">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:boolean">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="integer">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="integerList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="integer" type="xs:integer" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="long">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:long">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="longList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="long" type="xs:long" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="float">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="floatList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="float" type="xs:float" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="double">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:double">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="doubleList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="double" type="xs:double" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="string">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

   <!--
    Objects of this class could be used instead of {@link java.lang.String} to
    hold text strings with newlines in it. SimpleTypes with values wrapped in
    objects of this class will show up in the UI as multiline text areas.
   -->
    <xs:element name="text">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="stringList">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="string" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="name" use="required" type="xs:string"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="date">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:dateTime">
                    <xs:attribute name="name" use="required" type="xs:string"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:element name="map">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="namedTypes">
                    <xs:attribute name="class" type="xs:string"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="mapId">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="object" type="namedTypes">
        <xs:unique name="objectFieldId">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:element name="newObject">
        <xs:complexType>
            <xs:complexContent>
                <xs:extension base="namedTypes">
                    <xs:attribute name="class" type="xs:string"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
        <xs:unique name="newObjectFieldId">
            <xs:selector xpath="./*"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="basicTypes">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="object"/>
            <xs:element ref="newObject"/>
            <xs:element ref="boolean"/>
            <xs:element ref="integer"/>
            <xs:element ref="long"/>
            <xs:element ref="float"/>
            <xs:element ref="string"/>
            <xs:element ref="date"/>
            <xs:element ref="integerList"/>
            <xs:element ref="longList"/>
            <xs:element ref="stringList"/>
            <xs:element ref="text"/>
            <xs:element ref="map"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="namedTypes">
        <xs:complexContent>
            <xs:extension base="basicTypes">
                <xs:attribute name="name" use="required" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== netarchivesuite/netarchivesuite/harvester/harvester/src/test/resources/dk/netarkivet/harvester/datamodel/data/hadebasedir/order_templates/Max_20_2-order.xml
<?xml version="1.0" encoding="UTF-8"?>
<crawl-order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="heritrix_settings.xsd">
    <meta>
        <name>Max_20_2-order</name>
        <description>Default Profile</description>
        <operator>Admin</operator>
        <organization/>
        <audience>TESTERS</audience>
        <date>20080118111217</date>
    </meta>
    <controller>
        <string name="settings-directory">settings</string>
        <string name="disk-path"/>
        <string name="logs-path">logs</string>
        <string name="checkpoints-path">checkpoints</string>
        <string name="state-path">state</string>
        <string name="scratch-path">scratch</string>
        <long name="max-bytes-download">0</long>
        <long name="max-document-download">20</long>
        <long name="max-time-sec">0</long>
        <integer name="max-toe-threads">50</integer>
        <integer name="recorder-out-buffer-bytes">4096</integer>
        <integer name="recorder-in-buffer-bytes">65536</integer>
        <integer name="bdb-cache-percent">0</integer>
	<!-- DecidingScope migrated from DomainScope -->
        <newObject name="scope" class="org.archive.crawler.deciderules.DecidingScope">
            <boolean name="enabled">true</boolean>
            <string name="seedsfile">seeds.txt</string>
            <boolean name="reread-seeds-on-config">true</boolean>
            <!-- DecideRuleSequence. Multiple DecideRules applied in order with last non-PASS the resulting decision -->
            <newObject name="decide-rules" class="org.archive.crawler.deciderules.DecideRuleSequence">

        	<map name="rules">
			<newObject name="rejectByDefault" class="org.archive.crawler.deciderules.RejectDecideRule"/>
			<newObject name="acceptURIFromSeedDomains" class="dk.netarkivet.harvester.harvesting.OnNSDomainsDecideRule">
            			<string name="decision">ACCEPT</string>
            			<string name="surts-source-file"></string>
            			<boolean name="seeds-as-surt-prefixes">true</boolean>
            			<string name="surts-dump-file"/>
            			<boolean name="also-check-via">false</boolean>
            			<boolean name="rebuild-on-reconfig">true</boolean>
          		</newObject>

            		<newObject name="rejectIfTooManyHops" class="org.archive.crawler.deciderules.TooManyHopsDecideRule">
            			<integer name="max-hops">0</integer>
          		</newObject>
			<newObject name="rejectIfPathological" class="org.archive.crawler.deciderules.PathologicalPathDecideRule">
            			<integer name="max-repetitions">3</integer>
          		</newObject>
			<newObject name="acceptIfTranscluded" class="org.archive.crawler.deciderules.TransclusionDecideRule">
            			<integer name="max-trans-hops">3</integer>
            			<integer name="max-speculative-hops">1</integer>
          		</newObject>
			<newObject name="pathdepthfilter" class="org.archive.crawler.deciderules.TooManyPathSegmentsDecideRule">
            			<integer name="max-path-depth">20</integer>
          		</newObject>

                        <newObject name="webbyen" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*webbyen.*kontakt\.asp.*</string>
          		</newObject>
			<newObject name="dr_dk" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*dr\.dk.*epg\.asp.*</string>
          		</newObject>
			<newObject name="stiften" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*stiften.*adstream_mjx\.ads.*</string>
          		</newObject>
			<newObject name="halibut_dk" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*halibut\.dk\/cgi-bin.*</string>
          		</newObject>
			<newObject name="cybercomputer_dk" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*cybercomputer\.dk\/putikurv.*</string>
          		</newObject>
			<newObject name="tawselovers_dk" class="org.archive.crawler.deciderules.MatchesRegExpDecideRule">
            			<string name="decision">REJECT</string>
            			<string name="regexp">.*tawselovers.*action=buy_now.*</string>
          		</newObject>
		</map> <!-- end rules -->
            </newObject> <!-- end decide-rules -->
        </newObject> <!-- End DecidingScope -->
        <map name="http-headers">
            <string name="user-agent">Mozilla/5.0 (compatible; heritrix/1.5.0-200506132127 +http://netarkivet.dk/website/info.html)</string>
            <string name="from">netarkivet-svar@netarkivet.dk</string>
        </map>
        <newObject name="robots-honoring-policy" class="org.archive.crawler.datamodel.RobotsHonoringPolicy">
            <string name="type">ignore</string>
            <boolean name="masquerade">false</boolean>
            <text name="custom-robots"/>
            <stringList name="user-agents">
            </stringList>
        </newObject>
        <newObject name="frontier" class="org.archive.crawler.frontier.BdbFrontier">
            <float name="delay-factor">1.0</float>
            <integer name="max-delay-ms">1000</integer>
            <integer name="min-delay-ms">300</integer>
            <integer name="max-retries">3</integer>
            <long name="retry-delay-seconds">300</long>
            <integer name="preference-embed-hops">1</integer>
            <integer name="total-bandwidth-usage-KB-sec">1500</integer>
            <integer name="max-per-host-bandwidth-usage-KB-sec">500</integer>
            
        <string name="queue-assignment-policy">dk.netarkivet.harvester.harvesting.DomainnameQueueAssignmentPolicy</string>
    
            <string name="force-queue-assignment"/>
            <boolean name="pause-at-start">false</boolean>
            <boolean name="pause-at-finish">false</boolean>
            <boolean name="source-tag-seeds">false</boolean>
            <boolean name="recovery-log-enabled">false</boolean>
            <boolean name="hold-queues">true</boolean>
            <integer name="balance-replenish-amount">3000</integer>
            <integer name="error-penalty-amount">100</integer>
            <long name="queue-total-budget">-1</long>
            <string name="cost-policy">org.archive.crawler.frontier.UnitCostAssignmentPolicy</string>
            <long name="snooze-deactivate-ms">300000</long>
	    <integer name="target-ready-backlog">50</integer>	
            <string name="uri-included-structure">org.archive.crawler.util.BdbUriUniqFilter</string>
        </newObject>

        <map name="uri-canonicalization-rules">
            <newObject name="Lowercase" class="org.archive.crawler.url.canonicalize.LowercaseRule">
                <boolean name="enabled">true</boolean>
            </newObject>
            <newObject name="Userinfo" class="org.archive.crawler.url.canonicalize.StripUserinfoRule">
                <boolean name="enabled">true</boolean>
            </newObject>
            <newObject name="WWW" class="org.archive.crawler.url.canonicalize.StripWWWRule">
                <boolean name="enabled">false</boolean>
            </newObject>
            <newObject name="SessionIDs" class="org.archive.crawler.url.canonicalize.StripSessionIDs">
                <boolean name="enabled">true</boolean>
            </newObject>
            <newObject name="QueryStrPrefix" class="org.archive.crawler.url.canonicalize.FixupQueryStr">
                <boolean name="enabled">true</boolean>
            </newObject>
        </map>
        <!-- Heritrix pre-fetch processors -->
        <map name="pre-fetch-processors">

            <newObject name="QuotaEnforcer" class="org.archive.crawler.prefetch.QuotaEnforcer">
                <boolean name="force-retire">false</boolean>
    		<boolean name="enabled">true</boolean>
		<newObject name="QuotaEnforcer#decide-rules" class="org.archive.crawler.deciderules.DecideRuleSequence">
          		<map name="rules">
          		</map>
		</newObject>
              <long name="server-max-fetch-successes">-1</long>
              <long name="server-max-success-kb">-1</long>
              <long name="server-max-fetch-responses">-1</long>
              <long name="server-max-all-kb">-1</long>

              <long name="host-max-fetch-successes">-1</long>
              <long name="host-max-success-kb">-1</long>
              <long name="host-max-fetch-responses">-1</long>
              <long name="host-max-all-kb">-1</long>

              <long name="group-max-fetch-successes">-1</long>
              <long name="group-max-success-kb">-1</long>
              <long name="group-max-fetch-responses">-1</long>
              <long name="group-max-all-kb">-1</long>

            </newObject>

            <newObject name="Preselector" class="org.archive.crawler.prefetch.Preselector">
                <boolean name="enabled">true</boolean>
		<newObject name="Preselector#decide-rules" class="org.archive.crawler.deciderules.DecideRuleSequence">
          		<map name="rules">
          		</map>
		</newObject>
                <boolean name="override-logger">false</boolean>
                <boolean name="recheck-scope">true</boolean>
                <boolean name="block-all">false</boolean>
                <string name="block-by-regexp"/>
		<string name="allow-by-regexp"/>
            </newObject>
            <newObject name="Preprocessor" class="org.archive.crawler.prefetch.PreconditionEnforcer">
                <boolean name="enabled">true</boolean>
		<newObject name="Preprocessor#decide-rules" class="org.archive.crawler.deciderules.DecideRuleSequence">
